/*
 * GENERATED by scripts/trace-zoning-sheets.py. Do not edit; re-run the script.
 *
 * Which barangays have a traced zoning layer, and where it is. The layers
 * themselves are fetched on demand from web/public/zoning/, never bundled:
 * together they are ~0.5 MB and an applicant needs one.
 *
 * A barangay missing here has no credible tracing; the map shows no zoning
 * layer for it rather than a wrong one. See the script for how and why.
 */

/** Keyed by barangay name as `malabonGeo.data.ts` spells it. */
export const ZONING_LAYERS: Record<string, string> = {
  "Acacia": "/zoning/acacia.geojson",
  "Baritan": "/zoning/baritan.geojson",
  "Bayan-bayanan": "/zoning/bayan-bayanan.geojson",
  "Catmon": "/zoning/catmon.geojson",
  "Concepcion": "/zoning/concepcion.geojson",
  "Dampalit": "/zoning/dampalit.geojson",
  "Flores": "/zoning/flores.geojson",
  "Hulong Duhat": "/zoning/hulong-duhat.geojson",
  "Ibaba": "/zoning/ibaba.geojson",
  "Longos": "/zoning/longos.geojson",
  "Maysilo": "/zoning/maysilo.geojson",
  "Muzon": "/zoning/muzon.geojson",
  "Niugan": "/zoning/niugan.geojson",
  "Panghulo": "/zoning/panghulo.geojson",
  "Potrero": "/zoning/potrero.geojson",
  "San Agustin": "/zoning/san-agustin.geojson",
  "Santulan": "/zoning/santulan.geojson",
  "Tañong": "/zoning/tanong.geojson",
  "Tinajeros": "/zoning/tinajeros.geojson",
  "Tonsuya": "/zoning/tonsuya.geojson",
  "Tugatog": "/zoning/tugatog.geojson",
}
