<?php

use App\Support\RenewalModelAnalytics;

/*
 * The fitted renewal-risk model, checked against the payload it has to keep
 * producing.
 *
 * This model used to be fitted by a separate statistics runtime that Laravel
 * posted a dataset to. That runtime has been removed and the fit was ported into
 * RenewalModelAnalytics and Glm. The obvious risk in a port like that is not that
 * it fails — a broken IRLS loop announces itself — but that it QUIETLY DISAGREES:
 * a slightly different convergence rule, a quantile definition off by one
 * interpolation, a factor level folded in a different order, and the coefficient
 * table still looks entirely reasonable while every number in it has moved.
 *
 * So the check is not "does it produce plausible statistics". It is: here is a
 * real dataset, captured off the live register; here is the exact payload the
 * previous engine returned for it, byte for byte as it went over the wire; and
 * compute() must reproduce that payload. Both files are frozen fixtures and
 * neither was generated by the implementation they are checking.
 *
 *   INPUT     tests/fixtures/analytics/renewal-model.dataset.json
 *   EXPECTED  tests/fixtures/analytics/renewal-model.expected.json
 *
 * Nothing here starts a service, opens a socket or touches the database.
 * compute() is a pure function of its dataset, which is what makes this test
 * possible and is a property worth keeping for that reason alone.
 *
 * ── ON THE TOLERANCE ────────────────────────────────────────────────────────
 *
 * Every figure in the expected payload is already rounded — three decimal places
 * for the statistics, three significant figures for the p-values — so agreement
 * is expected to be exact and the tolerance exists only to absorb the last bit of
 * a float that was written out as decimal text and read back. It is deliberately
 * far tighter than the rounding: at 1e-9 a genuine disagreement in the third
 * decimal place cannot slip through, which is the entire point. Widening this
 * constant to make a failure go away would delete the test.
 */

const FIT_TOLERANCE = 1.0e-9;

/**
 * @return array<string, mixed>
 */
function renewalModelFixture(string $name): array
{
    $path = __DIR__."/../fixtures/analytics/renewal-model.{$name}.json";

    expect(file_exists($path))->toBeTrue("Missing fixture: {$path}");

    /** @var array<string, mixed> $decoded */
    $decoded = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

    return $decoded;
}

/**
 * Compare two payloads structurally, reporting the PATH of the first
 * disagreement rather than dumping two thousand-line arrays at the reader.
 *
 * Numbers are compared with a tolerance; everything else is compared strictly,
 * because a label, a reason or a state is either the sentence the screen shows or
 * it is a regression. Both directions of key membership are checked: a key the
 * port invented is as much a break of the contract as one it dropped.
 */
function expectPayloadMatches(mixed $actual, mixed $expected, string $path = '$'): void
{
    if (is_array($expected)) {
        expect($actual)->toBeArray("[{$path}] should be an array");

        $expectedKeys = array_keys($expected);
        $actualKeys = array_keys($actual);
        sort($expectedKeys);
        sort($actualKeys);

        expect($actualKeys)->toBe($expectedKeys, sprintf(
            "[%s] has the wrong keys.\n  Missing: %s\n  Extra:   %s",
            $path,
            implode(', ', array_diff($expectedKeys, $actualKeys)) ?: '—',
            implode(', ', array_diff($actualKeys, $expectedKeys)) ?: '—',
        ));

        foreach ($expected as $key => $child) {
            expectPayloadMatches($actual[$key], $child, "{$path}.{$key}");
        }

        return;
    }

    if (is_int($expected) || is_float($expected)) {
        expect(is_int($actual) || is_float($actual))->toBeTrue(
            "[{$path}] should be a number, got ".var_export($actual, true),
        );

        expect(abs((float) $actual - (float) $expected))->toBeLessThanOrEqual(
            // Relative for the tiny ones: a p-value of 1.58e-32 cannot be
            // compared on an absolute scale without the comparison passing for
            // any wrong answer at all.
            max(FIT_TOLERANCE, abs((float) $expected) * FIT_TOLERANCE),
            sprintf('[%s] expected %s, got %s', $path, var_export($expected, true), var_export($actual, true)),
        );

        return;
    }

    expect($actual)->toBe($expected, "[{$path}] differs");
}

it('reproduces the golden payload from the golden dataset', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));
    $expected = renewalModelFixture('expected');

    /*
     * ── THE ONE VALUE THAT IS DELIBERATELY NOT REPRODUCED ───────────────────
     *
     * `engine` is a caption, not a statistic. In the captured payload it reads
     * `glm(family = binomial)` — the literal call signature of the function in
     * the statistics runtime that used to fit this model. That string is printed
     * verbatim on the screen, so to a reader who recognises it, it asserts a
     * provenance that stopped being true when the runtime was removed.
     *
     * So it now names the method instead of a vendor's spelling of it. Both sides
     * are pinned here rather than the comparison being loosened, so this stays a
     * single recorded exception: if the caption drifts again, or if the fixture is
     * ever regenerated, one of these two lines fails and somebody has to decide
     * on purpose. Every other value in the payload — every coefficient, standard
     * error, p-value, bin bound and sentence — is reproduced exactly.
     */
    expect($payload['engine'])->toBe('logistic regression, fitted by IRLS');
    expect($expected['engine'])->toBe('glm(family = binomial)');
    $expected['engine'] = $payload['engine'];

    expectPayloadMatches($payload, $expected);
});

/*
 * The block below asserts the same fixture a second time, by hand, at the
 * headline figures. It is not redundant with the walk above: when a structural
 * comparison fails it says one path, and these say WHICH KIND of thing broke —
 * the fit, the split, the folding policy, or the prose. The values are read off
 * the frozen expected payload, never off this implementation's output.
 */

it('fits the five coefficients the training rows support', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    expect($payload['available'])->toBeTrue();
    expect($payload['unavailable_reason'])->toBeNull();

    $byTerm = array_column($payload['coefficients'], null, 'term');

    expect(array_keys($byTerm))->toBe([
        '(Intercept)', 'time_remaining', 'punctuality_known', 'prior_late_rate', 'open_findings',
    ]);

    expect($byTerm['(Intercept)']['estimate'])->toBe(5.475);
    expect($byTerm['(Intercept)']['std_error'])->toBe(0.461);
    expect($byTerm['(Intercept)']['z_value'])->toBe(11.876);

    // Longer left, less likely late; the sign here is the model's one claim a
    // licensing officer can check against their own experience.
    expect($byTerm['time_remaining']['estimate'])->toBe(-1.086);
    expect($byTerm['time_remaining']['z_value'])->toBe(-10.981);
    expect($byTerm['time_remaining']['interpretation'])
        ->toBe('Each doubling of the days left lowers the odds of a late renewal, by a factor of 0.47.');

    expect($byTerm['punctuality_known']['estimate'])->toBe(0.756);
    expect($byTerm['prior_late_rate']['estimate'])->toBe(-1.801);

    // The one term the data does not support, reported as such rather than
    // quietly omitted from a table the screen presents as complete.
    expect($byTerm['open_findings']['estimate'])->toBe(0.05);
    expect($byTerm['open_findings']['significant'])->toBeFalse();
});

it('folds thin factor levels away and says which, and why, in words', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    expect(array_column($payload['dropped'], 'term'))->toBe([
        'renewal_stagein_progress',
        'renewal_stagerejected',
        'fee_stateunpaid',
        'renewal_stage',
        'fee_state',
    ]);

    $byTerm = array_column($payload['dropped'], null, 'term');

    // Seventeen rows that all went the same way have no finite coefficient — the
    // distinction between "too few rows" and "no finite answer exists" is the
    // whole reason the reasons are two different sentences.
    expect($byTerm['renewal_stagein_progress']['reason'])->toBe(
        "all 17 training rows went the same way, so no finite coefficient exists for it — folded in with 'none'",
    );
    expect($byTerm['renewal_stagerejected']['reason'])->toBe(
        "only 22 training rows, below the 25 needed to estimate it — folded in with 'none'",
    );

    // A level that never occurs in the training period is not "dropped" — it did
    // not happen — so `draft` and `returned` are absent from this list entirely.
    expect($byTerm)->not->toHaveKey('renewal_stagedraft');
    expect($byTerm)->not->toHaveKey('renewal_stagereturned');

    // Folding leaves both factors on one level, at which point they explain
    // nothing and the terms themselves go.
    expect($byTerm['renewal_stage']['reason'])
        ->toBe('only one value (none) appears in the training period, so it explains nothing');
    expect($byTerm['fee_state']['reason'])
        ->toBe('only one value (settled) appears in the training period, so it explains nothing');
});

it('splits by time and reports what it was marked on', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    // A random split would let the model see the future it is scored against.
    expect($payload['split']['random'])->toBeFalse();
    expect($payload['split']['train_to'] <= $payload['split']['test_from'])->toBeTrue();
    expect($payload['split']['train_from'])->toBe('2024-09-12');
    expect($payload['split']['test_to'])->toBe('2025-12-01');

    expect($payload['training'])->toBe(['cycles' => 588, 'observations' => 1109, 'late' => 865, 'late_rate' => 0.78]);
    expect($payload['evaluation'])->toBe(['cycles' => 252, 'observations' => 422, 'late' => 255, 'late_rate' => 0.604]);

    expect($payload['metrics']['observations'])->toBe(422);
    expect($payload['metrics']['unfitted_levels'])->toBe(0);
});

it('reports discrimination, accuracy and skill against a fixed-rate baseline', function () {
    $metrics = RenewalModelAnalytics::compute(renewalModelFixture('dataset'))['metrics'];

    expect($metrics['auc'])->toBe(0.786);
    expect($metrics['brier'])->toBe(0.214);
    expect($metrics['baseline_brier'])->toBe(0.27);
    expect($metrics['skill_score'])->toBe(0.209);
});

it('holds the clock still and shows how little separation is left when it does', function () {
    $horizon = RenewalModelAnalytics::compute(renewalModelFixture('dataset'))['horizon_auc'];

    // Descending lead time, one row per lead the evaluation set holds.
    expect(array_column($horizon, 'days_to_expiry'))->toBe([180, 90, 60, 30, 15, 7, 1]);

    $byLead = array_column($horizon, null, 'days_to_expiry');

    // The honest reading of this model: pooled AUC 0.786, but within a single
    // lead it is barely above a coin toss. Most of the pooled figure is the
    // calendar. If this assertion ever starts passing with 0.9s, the split has
    // sprung a leak.
    expect($byLead[180]['auc'])->toBe(0.538);
    expect($byLead[30]['auc'])->toBe(0.647);

    // Every cycle one day out was late, so there is nothing to separate and AUC
    // is undefined — reported as null, not as 0.5.
    expect($byLead[1]['late_rate'])->toBe(1.0);
    expect($byLead[1]['auc'])->toBeNull();
});

it('bins the evaluation set by decile and states the calibration finding bluntly', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    expect($payload['calibration'])->toHaveCount(10);
    expect(array_column($payload['calibration'], 'bin'))->toBe([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);

    // Equal-count bins, so each carries the bounds of the predicted values that
    // fell in it and the observed rate that resulted.
    expect($payload['calibration'][0])->toBe([
        'bin' => 1, 'observations' => 52, 'predicted' => 0.453, 'observed' => 0.346,
        'lower' => 0.351, 'upper' => 0.47,
    ]);
    expect($payload['calibration'][9]['observed'])->toBe(1.0);

    expect($payload['metrics']['calibration_slope'])->toBe(0.94);
    expect($payload['metrics']['calibration_intercept'])->toBe(-0.977);

    // The verdict, and it is a failing one: the model ranks well and its numbers
    // run high. `calibrated => false` is what stops the screen calling this
    // figure a probability.
    expect($payload['metrics']['calibrated'])->toBeFalse();
    expect($payload['calibration_statement'])->toBe(
        'They run high: the model predicts 77% late across the evaluation period where 60% actually were. '
        .'The spread is about right (slope 0.94 against an ideal 1.00). '
        .'Across the risk deciles the largest gap between predicted and observed is 37 percentage points.',
    );
});

it('offers no estimate where there is nothing left to estimate', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    expect($payload['estimates'])->toHaveCount(25);

    foreach ($payload['estimates'] as $estimate) {
        if ($estimate['state'] !== 'open') {
            expect($estimate['probability'])->toBeNull(
                "A permit in state [{$estimate['state']}] was given a figure anyway.",
            );
        }

        // The rule score travels beside the fitted figure, always, so the screen
        // can show both and the reader can tell the two kinds of claim apart.
        expect($estimate)->toHaveKeys(['rule_score', 'rule_band', 'rule_band_label']);
    }

    // Every permit on this watchlist is already past its expiry date, so the
    // lateness is a fact and the whole table is reasons rather than figures.
    expect(array_unique(array_column($payload['estimates'], 'state')))->toBe(['lapsed']);
    expect($payload['estimates'][0]['state_label'])->toBe('Already lapsed — the renewal is late');
});

it('carries the training-data notice, which outranks every figure above', function () {
    $payload = RenewalModelAnalytics::compute(renewalModelFixture('dataset'));

    expect($payload['training_data']['synthetic'])->toBeTrue();
    expect($payload['training_data']['notice'])->toBe(RenewalModelAnalytics::TRAINING_DATA_NOTICE);
    expect(mb_strtolower($payload['training_data']['notice']))->toContain('demonstration data');
    expect($payload['methodology'])->toBe(RenewalModelAnalytics::METHODOLOGY);
});

it('refuses to fit rather than fitting something worthless, and says which shortfall', function () {
    $dataset = renewalModelFixture('dataset');

    // No labelled history at all.
    expect(RenewalModelAnalytics::compute(['rows' => [], 'split' => ['cutoff' => '2025-06-16']])['unavailable_reason'])
        ->toBe('no_labelled_history');

    // History, but no cutoff to split it on.
    $noCutoff = $dataset;
    $noCutoff['split']['cutoff'] = null;
    expect(RenewalModelAnalytics::compute($noCutoff)['unavailable_reason'])->toBe('no_labelled_history');

    // Plenty of rows, but fewer than MINIMUM_OBSERVATIONS of them before the
    // cutoff. Coefficients from eighty rows are noise wearing a standard error.
    $thin = $dataset;
    $thin['minimum_observations'] = 5000;
    expect(RenewalModelAnalytics::compute($thin)['unavailable_reason'])->toBe('not_enough_training_history');

    // A training period in which everything went the same way.
    $onesided = $dataset;
    $onesided['rows'] = array_map(static function (array $row): array {
        if ($row['split'] === 'train') {
            $row['late'] = 1;
        }

        return $row;
    }, $dataset['rows']);
    expect(RenewalModelAnalytics::compute($onesided)['unavailable_reason'])->toBe('not_enough_training_history');

    // Nothing after the cutoff to mark the model on. A model reporting its own
    // training accuracy is the failure this whole split exists to prevent.
    $noTest = $dataset;
    $noTest['rows'] = array_values(array_filter(
        $dataset['rows'],
        static fn (array $row): bool => $row['split'] === 'train',
    ));
    expect(RenewalModelAnalytics::compute($noTest)['unavailable_reason'])->toBe('not_enough_evaluation_history');

    // Every signal constant, so there is nothing for a coefficient to be about.
    $flat = $dataset;
    $flat['rows'] = array_map(static function (array $row): array {
        return [...$row, 'days_to_expiry' => 30, 'punctuality_known' => 0,
            'prior_late_rate' => 0, 'open_findings' => 0,
            'renewal_stage' => 'none', 'fee_state' => 'settled'];
    }, $dataset['rows']);
    expect(RenewalModelAnalytics::compute($flat)['unavailable_reason'])->toBe('no_signal_varies');
});

/*
 * The shape contract between the fitted answer and the refusal — one screen
 * reads both, so both carry the same keys — lives in
 * tests/Feature/RenewalModelKeyParityTest.php, which is the file named for it.
 */
