<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1a1a1a; margin: 0; padding: 40px; position: relative; }
        .watermark {
            position: fixed; top: 40%; left: 8%;
            transform: rotate(-30deg);
            font-size: 60px; font-weight: bold; color: #bd0000;
            opacity: 0.12; letter-spacing: 4px; z-index: 0;
        }
        .content { position: relative; z-index: 1; }
        .header { text-align: center; border-bottom: 3px solid #0025cc; padding-bottom: 12px; }
        .header .city { font-size: 20px; font-weight: bold; color: #0025cc; }
        .header .office { font-size: 12px; color: #333; }
        .title { text-align: center; font-size: 16px; font-weight: bold; margin: 20px 0; letter-spacing: 2px; }
        table.meta { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.meta td { padding: 5px 8px; font-size: 12px; }
        table.meta td.label { color: #666; width: 35%; }
        table.meta td.value { font-weight: bold; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.items th { background: #f0f2ff; text-align: left; padding: 8px; font-size: 11px; border-bottom: 2px solid #0025cc; }
        table.items td { padding: 8px; font-size: 12px; border-bottom: 1px solid #eee; }
        table.items td.amt { text-align: right; }
        .total-row td { font-weight: bold; font-size: 14px; border-top: 2px solid #333; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <div class="watermark">SIMULATED PAYMENT</div>
    <div class="content">
        <div class="header">
            <div class="city">CITY OF MALABON</div>
            <div class="office">Official Payment Receipt (Simulated)</div>
        </div>

        <div class="title">OFFICIAL RECEIPT</div>

        <table class="meta">
            <tr><td class="label">Reference No.</td><td class="value">{{ $reference_number }}</td></tr>
            <tr><td class="label">Tracking ID</td><td class="value">{{ $tracking_id }}</td></tr>
            <tr><td class="label">Business</td><td class="value">{{ $business_name }}</td></tr>
            <tr><td class="label">Method</td><td class="value">{{ strtoupper($method) }}</td></tr>
            <tr><td class="label">Paid At</td><td class="value">{{ $paid_at }}</td></tr>
        </table>

        <table class="items">
            <thead>
                <tr><th>Description</th><th style="text-align:right">Amount (PHP)</th></tr>
            </thead>
            <tbody>
                @foreach($line_items as $item)
                    <tr>
                        <td>{{ $item['label'] ?? 'Fee' }}</td>
                        <td class="amt">{{ number_format((float)($item['amount'] ?? 0), 2) }}</td>
                    </tr>
                @endforeach
                <tr class="total-row">
                    <td>TOTAL PAID</td>
                    <td class="amt">{{ number_format((float)$total_amount, 2) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="footer">
            This receipt is for demonstration only. No real funds were collected. Generated by BizTrack.
        </div>
    </div>
</body>
</html>
