#!/usr/bin/env python3
"""
Keep docs/zoning-ordinance/rules.json honest and render rules.md from it.

    python3 scripts/zoning-rules.py           # refresh check lines, rewrite rules.md
    python3 scripts/zoning-rules.py --check   # exit 1 if either file is stale

rules.json is the inventory of every normative statement in City Ordinance
No. 24-2018 and is edited by hand. Two things in it are mechanical and go
stale as code moves, so this script owns them:

  - `implemented.check`, the file:line of each implemented rule's check. Found
    by the rule id quoted in the code ('V-2.1-HO-1'), or by the entry's
    `implemented.marker` where the check is not keyed by id (an inheritance
    chain, a payment gate in WorkflowService).
  - `status_counts` in the header.

rules.md is generated: never edit it by hand. ZoningRulesCatalogueTest checks
the claims (tests exist, lines exist, questions exist) on every Pest run.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = ROOT / 'docs/zoning-ordinance/rules.json'
MD = ROOT / 'docs/zoning-ordinance/rules.md'
SEARCH = [
    'api/app/Support/Zoning/ZoningCheck.php',
    'api/app/Support/Zoning/Ordinance.php',
    'api/app/Support/ZoningConformance.php',
    'api/app/Services/WorkflowService.php',
]
STATUS_WORDS = {
    'implemented': 'Implemented',
    'shown': 'Shown',
    'not_applicable': 'Not applicable',
    'question': 'Question for Malabon',
}


def locate(path: str, marker: str):
    file = ROOT / path
    if not file.is_file():
        return None
    for n, line in enumerate(file.read_text(encoding='utf-8').split('\n'), 1):
        if marker in line:
            return n
    return None


def refresh(doc: dict) -> list[str]:
    problems = []
    for rule in doc['rules']:
        if rule['status'] != 'implemented':
            continue
        impl = rule['implemented']
        current = impl['check'].split(':')[0]
        marker = impl.get('marker')
        found = None
        if marker:
            line = locate(current, marker)
            found = f'{current}:{line}' if line else None
        else:
            for path in [current] + [p for p in SEARCH if p != current]:
                line = locate(path, f"'{rule['id']}'")
                if line:
                    found = f'{path}:{line}'
                    break
        if found is None:
            problems.append(f"{rule['id']}: its check is no longer where rules.json says ({impl['check']})")
        else:
            impl['check'] = found
    counts = {}
    for rule in doc['rules']:
        counts[rule['status']] = counts.get(rule['status'], 0) + 1
    doc['status_counts'] = dict(sorted(counts.items()))
    return problems


def detail(rule: dict) -> str:
    status = rule['status']
    if status == 'implemented':
        check = rule['implemented']['check']
        test = rule['implemented']['test'].split('::', 1)
        out = f"checked at `{check}`; proved by `{test[0].split('/')[-1]}` — “{test[1]}”"
    elif status == 'shown':
        out = rule['shown']['where']
    elif status == 'not_applicable':
        out = rule['not_applicable']['reason']
    else:
        out = f"[{rule['question']['id']}](../questions-for-malabon.md) — asked of the City; until answered the check shows both readings or sends it to CPDO."
    if 'also_question' in rule:
        out += f" Also asked: [{rule['also_question']['id']}](../questions-for-malabon.md)."
    return out


def render(doc: dict) -> str:
    counts = doc['status_counts']
    total = sum(counts.values())
    lines = [
        '# City Ordinance No. 24-2018 — every rule, and what BizTrack does with it',
        '',
        '<!-- Generated by scripts/zoning-rules.py from rules.json. Do not edit by hand. -->',
        '',
        f"{total} normative statements, read from all 110 pages of the ordinance. "
        'Each is one of:',
        '',
        f"- **Implemented** ({counts.get('implemented', 0)}) — the zoning check evaluates it; the entry names the line and the test.",
        f"- **Shown** ({counts.get('shown', 0)}) — surfaced to the applicant or the zoning officer as information; the entry says where.",
        f"- **Not applicable** ({counts.get('not_applicable', 0)}) — cannot bear on a business filing; the entry says why.",
        f"- **Question for Malabon** ({counts.get('question', 0)}) — needs the City’s answer; linked to docs/questions-for-malabon.md.",
        '',
        'Citations give the page number printed on the ordinance. The verbatim text of every '
        'rule is in `rules.json`; it is quoted here for the ones the check implements or shows.',
        '',
    ]
    section = None
    for rule in doc['rules']:
        head = f"Article {rule['article']}" if not rule['article'].startswith('Annex') else rule['article']
        if head != section:
            section = head
            lines += ['', f'## {head}', '']
        lines.append(f"- **{rule['id']}** · {rule['citation']} — **{rule['title']}** · _{STATUS_WORDS[rule['status']]}_")
        lines.append(f"  {rule['plain']}")
        if rule['status'] in ('implemented', 'shown', 'question'):
            quote = rule['verbatim'].replace('\n', ' / ')
            if len(quote) > 600:
                quote = quote[:600].rsplit(' ', 1)[0] + ' …'
            lines.append(f'  > {quote}')
        lines.append(f"  {detail(rule)}")
    return '\n'.join(lines) + '\n'


def main() -> int:
    check_only = '--check' in sys.argv
    before_json = RULES.read_text(encoding='utf-8')
    doc = json.loads(before_json)
    problems = refresh(doc)
    after_json = json.dumps(doc, ensure_ascii=False, indent=2) + '\n'
    md = render(doc)
    if problems:
        print('\n'.join(problems), file=sys.stderr)
        return 1
    if check_only:
        stale = after_json != before_json or not MD.exists() or MD.read_text(encoding='utf-8') != md
        if stale:
            print('rules.json or rules.md is stale: run python3 scripts/zoning-rules.py', file=sys.stderr)
            return 1
        return 0
    RULES.write_text(after_json, encoding='utf-8')
    MD.write_text(md, encoding='utf-8')
    print(f"{len(doc['rules'])} rules: {doc['status_counts']}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
